language: python

python:
  - "2.7"

sudo: required  # Required for docker
services:
  - docker
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-dev
      - python-lxml  # because pip installation is slow
      - python-numpy
      - python-simplejson
      - python-serial
      - python-matplotlib  # For runbot badges


sudo: required  # Required for docker
services:
  - docker

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="vauxoo/odoo" INCLUDE=runbot_selftest,runbot_travis2docker,runbot_send_email
    # - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/Vauxoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install -r requirements.txt
  - if [[ "${TESTS}" == "1"  ]]; then ${TRAVIS_BUILD_DIR}/.travis_requirements.sh; fi

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
